# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoRealm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #以下追加
  pod 'RealmSwift'

  # Pods for TodoRealm

  target 'TodoRealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoRealmUITests' do
    # Pods for testing
  end

end
